export const DAILY_READING = {
  title: "Når man flytter til et nyt land – hvornår føler man sig egentlig hjemme?",
  metadata: ["Samfund", "10 min. læsning", "B2–C1"],
  paragraphs: [
    "At flytte til et andet land bliver ofte beskrevet som en praktisk proces. Man finder en bolig, får styr på papirarbejdet, lærer transportsystemet at kende og opdager efterhånden, hvor man køber dagligvarer. Efter nogle måneder kan hverdagen begynde at fungere næsten automatisk. Man ved, hvilken bus man skal tage, hvordan man bestiller tid hos lægen, og hvilken kø i supermarkedet der plejer at gå hurtigst.",
    "Alligevel er der stor forskel på at kunne fungere i et land og på faktisk at føle sig hjemme der.",
    "I begyndelsen lægger man ofte mærke til næsten alt. Måden folk taler sammen på. Hvornår butikkerne lukker. Hvordan fremmede opfører sig i offentlig transport. Hvilke ting kolleger taler om til frokost. Selv små handlinger kan kræve bevidste overvejelser.",
    "Skal man sige noget til personen ved siden af sig i elevatoren? Må man sætte sig her? Skal man tage skoene af, når man besøger nogen? Hvor direkte kan man være over for sin chef?",
    "For mennesker, der er vokset op i landet, er den slags spørgsmål sjældent spørgsmål overhovedet. De har lært svarene uden nødvendigvis at være klar over det.",
    "Det er en af grundene til, at integration ikke kun handler om sprog.",
    "Man kan godt kunne kommunikere grammatisk korrekt og stadig være usikker på, hvad en situation kræver. Omvendt kan en person med et begrænset ordforråd være dygtig til at aflæse sociale signaler og derfor virke mere hjemmevant.",
    "Sproget spiller dog en særlig rolle, fordi det både er et praktisk redskab og en adgangsbillet til dele af samfundet, som ellers kan være vanskelige at komme ind i.",
    "På en international arbejdsplads kan man måske klare sig glimrende på engelsk. Man kan arbejde, gå på restaurant, træne og ordne mange praktiske ting uden at bruge ret meget af det lokale sprog. I et land, hvor en stor del af befolkningen taler godt engelsk, kan det faktisk være overraskende let.",
    "Men netop denne bekvemmelighed kan blive en barriere.",
    "Hvis lokalbefolkningen automatisk skifter til engelsk, så snart de hører en accent, bliver det sværere at få de tusindvis af små samtaler, der normalt gør et sprog automatisk. Man kan studere grammatik og lære ord derhjemme, men det er noget andet spontant at skulle fortælle en historie, afbryde høfligt eller forstå en bemærkning, der bliver sagt hurtigt hen over et frokostbord.",
    "Der findes også en mere subtil sproglig grænse.",
    "Når man når et forholdsvis højt niveau, er problemet ikke længere nødvendigvis, at man ikke kan sige det, man vil sige. Man kan sige det. Men måske siger man det på en måde, som er lidt mere direkte, lidt mere formel eller bare anderledes, end en lokal person ville gøre.",
    "Det kan være frustrerende, fordi fremskridtet bliver sværere at få øje på. Som begynder er udviklingen tydelig: I sidste måned kunne man ikke bestille kaffe; nu kan man. Senere kan forskellen mellem to niveauer bestå i noget så lille som at vælge en mere naturlig præposition eller vide, hvornår en bestemt formulering lyder for højtidelig.",
    "Samtidig ændrer ens forhold til fejl sig ofte.",
    "I begyndelsen forventer man at lave fejl. Man er måske ligefrem stolt over at have gennemført en samtale på trods af dem. Efter flere års læring kan den samme fejl føles mere irriterende: Burde jeg ikke have lært det her nu?",
    "Men automatisering tager tid. At kende en regel og at anvende den spontant under en samtale er to forskellige færdigheder. Man kan sagtens vide, hvilken præposition der er korrekt, når man sidder med god tid, og alligevel vælge den forkerte, når man skal svare på to sekunder.",
    "Derfor er gentagelse så vigtig.",
    "Ikke nødvendigvis gentagelse i betydningen at læse den samme regel tyve gange, men at møde den samme konstruktion i forskellige sammenhænge og selv blive nødt til at bruge den igen. Først når man ikke længere aktivt skal tænke over formen, er den for alvor blevet en del af ens aktive sprog.",
    "Men sproget er kun én del af spørgsmålet om at høre til.",
    "Sociale relationer betyder mindst lige så meget. Man kan bo i et land i mange år og stadig have størstedelen af sit sociale liv blandt andre udlændinge. Det behøver ikke at være et problem. Internationale venskaber kan være både tætte og værdifulde.",
    "Alligevel kan det påvirke følelsen af at være en del af det samfund, man bor i.",
    "Venskaber er samtidig et område, hvor kulturelle forskelle let bliver misforstået. Hvis mennesker i et land generelt er langsommere til at invitere nye bekendte ind i deres private liv, kan en udlænding fortolke det som afvisning. Den lokale person tænker måske slet ikke over det.",
    "Omvendt kan den nytilflyttede komme fra en kultur, hvor man relativt hurtigt inviterer nye mennesker hjem, og derfor opleve den lokale omgangsform som kølig.",
    "Ingen af parterne behøver at have gjort noget forkert. De følger bare forskellige sociale forventninger.",
    "Efter længere tid sker der dog ofte noget interessant: De kulturelle forskelle holder op med at være så synlige.",
    "Man tænker ikke længere: Nu gør jeg noget på den danske måde. Man gør det bare.",
    "Det kan være små ting. Måden man står i kø på. Hvilke samtaleemner man synes passer til frokosten. Hvordan man skriver en besked til en kollega. Hvilken slags humor man forventer i en gruppe.",
    "På det tidspunkt kan det være svært selv at opdage, hvor meget man har ændret sig.",
    "Det bliver nogle gange først tydeligt, når man besøger sit oprindelige hjemland. Ting, der tidligere virkede helt normale, kan pludselig føles fremmede eller irriterende. Måske bliver man overrasket over støjniveauet, måden folk kommunikerer på eller en social regel, man aldrig tidligere havde lagt mærke til.",
    "Så opstår en mærkelig situation: Man føler sig ikke nødvendigvis hundrede procent hjemme i det nye land, men heller ikke helt som den person, der engang forlod det gamle.",
    "Det behøver ikke at betyde, at man står mellem to steder uden at høre til nogen steder. Man kan også se det som en udvidelse. Ens opfattelse af, hvad der er normalt, bliver mindre selvfølgelig.",
    "Man opdager, at mange ting, man tidligere betragtede som almindelig sund fornuft, i virkeligheden var kulturelle vaner.",
    "Det gælder eksempelvis forestillinger om arbejde, familie, høflighed, privatliv og venskab. Når man kun har levet i ét kulturelt miljø, er det let at tro, at ens egen måde blot er den naturlige måde. Først når man møder mennesker, der gør tingene anderledes, bliver ens egne normer synlige.",
    "På den måde kan det at bo i udlandet skabe en særlig form for afstand til ens egen kultur. Man holder ikke nødvendigvis mindre af den, men man bliver bedre til at betragte den udefra.",
    "Hvornår kan man så sige, at man er integreret?",
    "Der findes selvfølgelig juridiske og politiske definitioner, men på det personlige plan er spørgsmålet vanskeligere.",
    "Er man integreret, når man taler sproget? Når man har lokale venner? Når man forstår humoren? Når man følger med i landets politik? Eller først når man holder op med at tænke på sig selv som en person, der bor ‘i udlandet’?",
    "Måske findes der ikke et bestemt tidspunkt.",
    "Følelsen af at høre til opstår sandsynligvis gradvist gennem hundredvis af små erfaringer: den første samtale, hvor man glemmer, at man taler et fremmedsprog; den første lokale joke, man forstår med det samme; den første situation, hvor en nytilflyttet spørger én til råds om, hvordan noget fungerer.",
    "På et tidspunkt opdager man måske, at det sted, man engang skulle lære at navigere i, bare er blevet hverdagen.",
    "Og måske er det netop dét, der er det nærmeste, man kommer på at føle sig hjemme.",
  ],
} as const;

export const DAILY_DISCUSSION = {
  title: "Hvad vil det sige at være integreret?",
  introduction:
    "Integration bliver ofte diskuteret som et politisk spørgsmål, men ordet dækker også over en meget personlig proces. Man kan være økonomisk selvforsørgende og tale landets sprog uden nødvendigvis at føle sig som en del af samfundet. Omvendt kan man føle en stærk tilknytning til et land uden at have overtaget alle dets normer og vaner.",
  expressions: [
    ["at falde til", "gradvist at føle sig godt tilpas og hjemme et nyt sted"],
    ["at høre til", "at føle, at man er en naturlig del af et sted eller en gruppe"],
    ["at begå sig", "at kunne håndtere sociale eller praktiske situationer på en passende måde"],
    ["at tage noget til sig", "gradvist at acceptere eller begynde at bruge en idé, vane eller del af en kultur"],
    ["at holde fast i noget", "bevidst at bevare noget, selv om omgivelserne ændrer sig"],
    ["at være splittet mellem noget", "at føle sig trukket i forskellige retninger af to hensyn, identiteter eller ønsker"],
  ],
  questions: [
    "Hvad betyder det for dig personligt at høre til i et land? Hvilken rolle spiller sprog, venner, arbejde og kulturelle vaner?",
    "Når man flytter til et andet land, hvor meget synes du så, man bør tage den lokale kultur til sig, og hvilke ting er det rimeligt at holde fast i fra sin oprindelige kultur?",
    "Kan du komme i tanke om noget, som engang virkede fremmed eller besværligt i det land, du bor i, men som efterhånden er blevet så normalt, at du næsten ikke lægger mærke til det længere?",
  ],
} as const;
